### ISSUE TITLE
Inline ruby not properly highlighted

### ISSUE THREAD

**Issue by mitch-sge** [slim-template/ruby-slim.tmbundle#41] opened 2014-08-30 20:07 UTC
I am having a problem with inline ruby blocks not being highlighted. Here are 2 examples:

![image](https://cloud.githubusercontent.com/assets/6218802/4100097/379fde62-3081-11e4-9ecc-6df6a9547ca5.png)
- Line 1 has an extra space after `|school|` and is highlighted properly
  - However, the extra space is not visible, and is not included in the highlight background color
- Line 3 does NOT have an extra space after `|school|` and it does not get highlighted.

It seems that the highlighter is ignoring the last character when parsing the syntax. So if the last character is irrelevant, like a space, everything works fine. But if the last character is a non-whitespace, it breaks the highlighter.

This happens on other inline ruby elements:

![image](https://cloud.githubusercontent.com/assets/6218802/4100100/43afdcca-3081-11e4-9dbd-5542122482f4.png)

You can see:
- Line 1: Proper highlight, and background color goes to end of line
- Line 2: No highlight needed, but you can see the background color does not include the `d`
- Line 3: Proper highlight, but the background color does not include the last parenthesis

**Comment by kreintjes** [comment] 2016-09-29 09:17
@mitch-sge I can't seem to reproduce this issue (in SublimeText 3 build 3126 with RubySlim v2016.06.25.06.05.06). Is it possible this is already fixed and thus this issue can be closed?

**Comment by tshedor** [comment] 2017-09-16 18:45
@mitch-sge I'm going to close this out as it's been a while, and I cannot reproduce either. Please feel free to comment if you're able to reproduce it.

**Closed by tshedor** 2017-09-16 18:45 UTC
